{
 "title": "IMU",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "X Angle",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Imu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"XAng\")"
    }
   ]
  },
  {
   "title": "X Acceration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Imu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"XAcc\")"
    }
   ]
  },
  {
   "title": "Y Angle",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Imu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"YAng\")"
    }
   ]
  },
  {
   "title": "Y Acceleration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Imu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"YAcc\")"
    }
   ]
  },
  {
   "title": "Z Angle",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Imu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ZAng\")"
    }
   ]
  },
  {
   "title": "Z Accerleration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Imu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ZAcc\")"
    }
   ]
  }
 ]
}