{
 "title": "Iris Temperatures",
 "description": "Iris Temperatures Dashboard.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Keep Alive Temperatures (K)",
   "type": "timeseries",
   "description": "DeckD2TempKelvin",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"DeckD2TempKelvin\" or r[\"_field\"] == \"BattAdcTempKelvin\" or r[\"_field\"] == \"Heater_OffTempKelvin\" or r[\"_field\"] == \"Heater_OnTempKelvin\")"
    }
   ]
  },
  {
   "title": "Keep Alive Temperatures (K)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"DeckD2TempKelvin\" or r[\"_field\"] == \"BattAdcTempKelvin\")"
    }
   ]
  },
  {
   "title": "Internal Rover Thermistors (K)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"RoverTherm6_TMR1Kelvin\" or r[\"_field\"] == \"RoverTherm7_TMR2Kelvin\" or r[\"_field\"] == \"RoverTherm8_TMR3Kelvin\" or r[\"_field\"] == \"RoverTherm9_TMR4Kelvin\" or r[\"_field\"] == \"RoverTherm10_TMR5Kelvin\" or r[\"_field\"] == \"RoverTherm11_TMR6Kelvin\" or r[\"_field\"] == \"RoverTherm12_TMR7Kelvin\" or r[\"_field\"] == \"RoverTherm13_TMR6Kelvin\" or r[\"_field\"] == \"RoverTherm14_TMR7Kelvin\" or r[\"_field\"] == \"RoverTherm15_TMR8Kelvin\")"
    }
   ]
  },
  {
   "title": "RT1-6 SBC Thermistors (K)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"BoardTherm0_RT1Kelvin\" or r[\"_field\"] == \"BoardTherm1_RT2Kelvin\" or r[\"_field\"] == \"BoardTherm2_RT3Kelvin\" or r[\"_field\"] == \"BoardTherm3_RT4Kelvin\" or r[\"_field\"] == \"BoardTherm4_RT5Kelvin\" or r[\"_field\"] == \"BoardTherm5_RT6Kelvin\")"
    }
   ]
  }
 ]
}