{
 "title": "Positioning",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Signal Strength / Range",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"Rssi\")"
    }
   ]
  },
  {
   "title": "Acceleration Axes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"XAcc_MS2\" or r[\"_field\"] == \"YAcc_MS2\" or r[\"_field\"] == \"ZAcc_MS2\")"
    }
   ]
  },
  {
   "title": "Acceleration Magnitude",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"GravityMagnitude_MS2\")"
    }
   ]
  },
  {
   "title": "Lateral Accelerations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"XAcc_MS2\" or r[\"_field\"] == \"YAcc_MS2\")"
    }
   ]
  },
  {
   "title": "Acceleration Vector Orientation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MetaModImu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"RollAngleDeg\" or r[\"_field\"] == \"PitchAngleDeg\")"
    }
   ]
  },
  {
   "title": "Z Acceleration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"ZAcc_MS2\")"
    }
   ]
  }
 ]
}