{
 "title": "Iris Currents",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Motor Bus Current",
   "type": "timeseries",
   "description": "MetaModRoverPower_MotorBusCurrent",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"MetaModRoverPower_MotorBusCurrent\")"
    }
   ]
  },
  {
   "title": "Radio 3V3 Current",
   "type": "timeseries",
   "description": "MetaModRoverPower_Radio3V3Current",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"MetaModRoverPower_Radio3V3Current\")"
    }
   ]
  },
  {
   "title": "FPGA 3V3 Current",
   "type": "timeseries",
   "description": "MetaModRoverPower_Fpga3V3Current\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"MetaModRoverPower_Fpga3V3Current\")"
    }
   ]
  },
  {
   "title": "Hercules 3V3 Current",
   "type": "timeseries",
   "description": "MetaModRoverPower_Hercules3V3Current",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"MetaModRoverPower_Hercules3V3Current\")"
    }
   ]
  },
  {
   "title": "FPGA 1V2 Curent",
   "type": "timeseries",
   "description": "MetaModRoverPower_Fpga1V2Current ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"MetaModRoverPower_Fpga1V2Current \")"
    }
   ]
  },
  {
   "title": "Hercules 1V2 Current",
   "type": "timeseries",
   "description": "MetaModRoverPower_Hercules1V2Current",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"MetaModRoverPower_Hercules1V2Current\")"
    }
   ]
  }
 ]
}