{
 "title": "Communications",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GroundInterface Downlink Statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"GiLogsDownlinked\" or r[\"_field\"] == \"GiDownlinkSeqNum\" or r[\"_field\"] == \"GiTlmItemsDownlinked\" or r[\"_field\"] == \"GiPacketsTransmitted\")"
    }
   ]
  },
  {
   "title": "GroundInterface Uplink Statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"GiCmdsUplinked\" or r[\"_field\"] == \"GiCmdsSent\" or r[\"_field\"] == \"GiUplinkPktErrs\" or r[\"_field\"] == \"GiUplinkSeqNum\" or r[\"_field\"] == \"UdpRxPacketCount\")"
    }
   ]
  },
  {
   "title": "File Downlink Statistics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"GroundInterface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"GiAppBytesDownlinked\" or r[\"_field\"] == \"GiAppBytesReceived\" or r[\"_field\"] == \"GiPacketsTransmitted\")"
    }
   ]
  },
  {
   "title": "Uplink Events",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RadioGround\" or r[\"_measurement\"] == \"GroundInterface\" or r[\"_measurement\"] == \"CommandDispatcher\")\n  |> filter(fn: (r) => r[\"_field\"] == \"GiCommandReceived\" or r[\"_field\"] == \"Heartbeat\" or r[\"_field\"] == \"OpCodeCompleted\" or r[\"_field\"] == \"OpCodeDispatched\")"
    }
   ]
  },
  {
   "title": "Radio Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RadioGround\")\n  |> filter(fn: (r) => r[\"_field\"] == \"UptimeMs\")"
    }
   ]
  },
  {
   "title": "Radio Health Statistics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RadioGround\")\n  |> filter(fn: (r) => r[\"_field\"] == \"HerculesUdpInterlockCountingSemaphore\" or r[\"_field\"] == \"BadHercPacketCount\")"
    }
   ]
  }
 ]
}