{
 "title": "Iris Temperatures",
 "description": "Iris temperatures dashboard.",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Peregrine Deck Sensor (K)",
   "type": "timeseries",
   "description": "MetaModPeregrine_DeckD2TempKelvin",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"MetaModPeregrine_DeckD2TempKelvin\")"
    }
   ]
  },
  {
   "title": "Battery Sensor (K)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"WatchdogHeartbeat_BattAdcTempKelvin\")"
    }
   ]
  },
  {
   "title": "RT1-5 SBC (K)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"MetaModTemps_BoardTherm0Kelvin\" or r[\"_field\"] == \"MetaModTemps_BoardTherm1Kelvin\" or r[\"_field\"] == \"MetaModTemps_BoardTherm2Kelvin\" or r[\"_field\"] == \"MetaModTemps_BoardTherm3Kelvin\" or r[\"_field\"] == \"MetaModTemps_BoardTherm4Kelvin\" or r[\"_field\"] == \"MetaModTemps_BoardTherm5Kelvin\" or r[\"_field\"] == \"MetaModTemps_BoardTherm6Kelvin\")"
    }
   ]
  },
  {
   "title": "RT6-14 Internal (K)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"MetaModTemps_BoardTherm6Kelvin\" or r[\"_field\"] == \"MetaModTemps_BoardTherm7Kelvin\" or r[\"_field\"] == \"MetaModTemps_BoardTherm8Kelvin\" or r[\"_field\"] == \"MetaModTemps_BoardTherm9Kelvin\" or r[\"_field\"] == \"MetaModTemps_BoardTherm10Kelvin\" or r[\"_field\"] == \"MetaModTemps_BoardTherm11Kelvin\" or r[\"_field\"] == \"MetaModTemps_BoardTherm12Kelvin\" or r[\"_field\"] == \"MetaModTemps_BoardTherm13Kelvin\" or r[\"_field\"] == \"MetaModTemps_BoardTherm14Kelvin\")"
    }
   ]
  }
 ]
}