{
 "title": "Iris Currents",
 "time": { "from": "2024-01-15T04:39:12.490Z", "to": "2024-01-15T05:25:59.570Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Motor Bus (24V) Current",
   "type": "timeseries",
   "description": "MotorBusCurrent",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"MotorBusCurrent_mA\")"
    }
   ]
  },
  {
   "title": "Radio 3V3 Current",
   "type": "timeseries",
   "description": "Radio3V3Current",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"Radio3V3Current_mA\")"
    }
   ]
  },
  {
   "title": "FPGA 3V3 Current",
   "type": "timeseries",
   "description": "Fpga3V3Current\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"Fpga3V3Current_mA\")"
    }
   ]
  },
  {
   "title": "Hercules 3V3 Current",
   "type": "timeseries",
   "description": "Hercules3V3Current",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"Hercules3V3Current_mA\")"
    }
   ]
  },
  {
   "title": "FPGA 1V2 Current",
   "type": "timeseries",
   "description": "Fpga1V2Current ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"Fpga1V2Current_mA \")"
    }
   ]
  },
  {
   "title": "Hercules 1V2 Current",
   "type": "timeseries",
   "description": "Hercules1V2Current",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"iris\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"Hercules1V2Current_mA\")"
    }
   ]
  }
 ]
}