{
 "title": "Rover Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Rover Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: -1h)  // Adjust the time range as needed\n  |> filter(fn: (r) => r._measurement == \"TempC\")"
    }
   ]
  },
  {
   "title": "Rover 28V",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchDogInterface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Voltage28V\")"
    }
   ]
  },
  {
   "title": "Battery Thermistor",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchDogInterface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Batterythermistor\")"
    }
   ]
  },
  {
   "title": "Heating Control",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchdogHeartbeatTvac\")\n  |> filter(fn: (r) => r[\"_field\"] == \"HeatingControlEnabled\")"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchdogHeartbeatTvac\")\n  |> filter(fn: (r) => r[\"_field\"] == \"CurrentAmps\")"
    }
   ]
  },
  {
   "title": "Charge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mamph" } },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchdogHeartbeatTvac\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ChargeMah\")"
    }
   ]
  },
  {
   "title": "Mission Alerts",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"mission_alerts\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)"
    }
   ]
  },
  {
   "title": "Rover Events",
   "type": "logs",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"mission_events\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchDogInterface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"CameraImageCaptureComplete\" or r[\"_field\"] == \"CameraImageDownlinkComplete\" or r[\"_field\"] == \"OpCodeCompleted\" or r[\"_field\"] == \"OpCodeDispatched\" or r[\"_field\"] == \"SpecialMessage\" or r[\"_field\"] == \"WatchDogCmdReceived\" or r[\"_field\"] == \"AdcCurrentSensorReadingsReport\")"
    }
   ]
  }
 ]
}