{
 "title": "WatchDog Interface",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Battery Thermistor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchDogInterface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Batterythermistor\")"
    }
   ]
  },
  {
   "title": "Therm0",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchDogInterface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Therm0\")"
    }
   ]
  },
  {
   "title": "Therm1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchDogInterface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Therm1\")"
    }
   ]
  },
  {
   "title": "Therm2",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchDogInterface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Therm2\")"
    }
   ]
  },
  {
   "title": "Therm3",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchDogInterface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Therm3\")"
    }
   ]
  },
  {
   "title": "Therm4",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchDogInterface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Therm4\")"
    }
   ]
  },
  {
   "title": "Therm5",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchDogInterface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Therm5\")"
    }
   ]
  },
  {
   "title": "Rover 28V",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchDogInterface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Voltage28V\")"
    }
   ]
  },
  {
   "title": "Therm6",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchDogInterface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Therm6\")"
    }
   ]
  },
  {
   "title": "Therm7",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchDogInterface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Therm7\")"
    }
   ]
  },
  {
   "title": "Therm8",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchDogInterface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Therm8\")"
    }
   ]
  },
  {
   "title": "Battery Thermistor",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchDogInterface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Batterythermistor\")"
    }
   ]
  },
  {
   "title": "Therm9",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchDogInterface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Therm9\")"
    }
   ]
  },
  {
   "title": "Therm10",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchDogInterface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Therm10\")"
    }
   ]
  },
  {
   "title": "Therm11",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchDogInterface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Therm11\")"
    }
   ]
  },
  {
   "title": "Therm12",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchDogInterface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Therm12\")"
    }
   ]
  },
  {
   "title": "Therm13",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchDogInterface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Therm13\")"
    }
   ]
  },
  {
   "title": "Therm14",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchDogInterface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Therm14\")"
    }
   ]
  },
  {
   "title": "Therm15",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchDogInterface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Therm15\")"
    }
   ]
  }
 ]
}