{
 "title": "WatchDog Heartbeat Tvac",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Heating Control",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchdogHeartbeatTvac\")\n  |> filter(fn: (r) => r[\"_field\"] == \"HeatingControlEnabled\")"
    }
   ]
  },
  {
   "title": "Charge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mamph" } },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchdogHeartbeatTvac\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ChargeMah\")"
    }
   ]
  },
  {
   "title": "Adc Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchdogHeartbeatTvac\")\n  |> filter(fn: (r) => r[\"_field\"] == \"AdcTempKelvin\")"
    }
   ]
  },
  {
   "title": "Fuel Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchdogHeartbeatTvac\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FuelTempKelvin\")"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchdogHeartbeatTvac\")\n  |> filter(fn: (r) => r[\"_field\"] == \"CurrentAmps\")"
    }
   ]
  },
  {
   "title": "Heater Window Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchdogHeartbeatTvac\")\n  |> filter(fn: (r) => r[\"_field\"] == \"HeaterWindowKelvin\")"
    }
   ]
  },
  {
   "title": "Heater Setpoint Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WatchdogHeartbeatTvac\")\n  |> filter(fn: (r) => r[\"_field\"] == \"HeaterSetpointKelvin\")"
    }
   ]
  }
 ]
}